updated README and script

diff --git a/farmer b/farmer
--- a/farmer
+++ b/farmer
@@ -19,7 +19,7 @@ echo -e "Web site: https://clouderscloud.github.io/farmer/"
 pid=$$
 whereami=`pwd`
 home=${whereami}
-cd ${home}; stat canal fruits soils seeds &>/dev/null; if [ $? -ne 0 ]; then echo "Error: Required directories(canal, fruits, soils, seeds) are missing. Please make sure to clone most latest source"; exit 1; fi
+cd ${home}; stat canal fruits soils seeds &>/dev/null; if [ $? -ne 0 ]; then echo -e "\nError: Required directories(canal, fruits, soils, seeds) are missing. Please make sure to clone most latest source"; exit 1; fi
 umask 0027
 seconds=0
 canal_dir="${home}/canal";
@@ -49,3 +49,6 @@ function help() {
 }
 
 help
+
+echo -e "\nSorry ! Farmer is not yet ready, still in initial development stage. Please check back later"
+echo ""
