updated main script v1.0.2 and README

diff --git a/farmer b/farmer
--- a/farmer
+++ b/farmer
@@ -1,5 +1,4 @@
 #!/bin/bash
-
 #-----------------------------------------------------------------------------
 #    Farmer - A lightweight automation tool built for Linux machines
 #    Copyright (C) 2017  Manikumar Juttukonda <manikumar.juttukonda@gmail.com>
@@ -16,6 +15,13 @@
 #
 #    You should have received a copy of the GNU General Public License
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#-----------------------------------------------------------------------------
+# Current Stable Version: v1.0.2
+# Incremental change log:
+# 08/16/2017 : (v0.0.1)(alpha) Initial development build
+# 08/18/2017 : (v1.0) First stable release
+# 08/19/2017 : (v1.0.1) Background process manager
+# 08/20/2017 : (v1.0.2) Implemented GC for process cleanup
 #-----------------------------------------------------------------------------
 
 #variables
@@ -112,11 +118,22 @@ function farmer_sow() {
 	while [[ `pstree -pan ${pid} 2>/dev/null | cut -d"," -f2 | cut -d" " -f1 | wc -l` -ne 5 ]];
 	do
 		BACKGP=`pstree -pan ${pid} 2>/dev/null | cut -d"," -f2 | cut -d" " -f1 | wc -l`
-		echo "Waitig on ${BACKGP} threads to complete"
+		echo "Waitig on (${BACKGP}) thread(s) to complete"
 		sleep 10;
 	done
 	echo "All threads completed !"
 	echo -e "\nAll commands were executed on remote server(s). Please check logs[${canal_dir}/${seed}_*] for any errors"
+}
+
+function farmer_cleanup() {
+	echo -e "\nKill signal received"
+	echo "Initiating GC"
+	while [[ `pstree -pan ${pid} 2>/dev/null | grep -v ${pid} | cut -d"," -f2 | cut -d" " -f1 | wc -l` -gt 4 ]];
+	do
+		kill -9 `pstree -pan ${pid} 2>/dev/null | grep -v ${pid} | cut -d"," -f2 | cut -d" " -f1 | tr '\n' ' '` 2>/dev/null 1>/dev/null
+	done
+	echo "Process cleanup completed"
+	exit 1
 }
 
 function farmer_harvest() {
@@ -126,6 +143,8 @@ function farmer_harvest() {
 }
 
 #start
+trap 'farmer_cleanup; exit 1' SIGHUP SIGINT SIGTERM
+
 if [ $# -lt 1 ]; then
 	echo ""
 	echo "Error #101: Not enough arguments"
@@ -150,7 +169,7 @@ echo -e '
 
 '
 
-#main start
+#kickstart
 case $1 in
 	sow )
 		if [ $# -ne 7 ]; then
