updated v2.0.0

diff --git a/farmer b/farmer
--- a/farmer
+++ b/farmer
@@ -73,6 +73,8 @@ help() {
 
 farmer_info() {
 	echo ""
+	echo "// ** Invoking farmer 'info' operation ** //"
+	echo ""
 	echo "Info: Farmer is verifying the quality of seeds and soils"
 	echo ""
         echo "  Soil check: $soil"
@@ -108,6 +110,8 @@ farmer_info() {
 
 farmer_sow() {
 	echo ""
+        echo "// ** Invoking farmer 'sow' operation ** //"
+	echo ""
 	echo "Info: Farmer is deploying seeds in soils"
 	rm $canal_dir/${seed}_${pid}.sh &>/dev/null
 	echo "#!/bin/bash -e" >> $canal_dir/${seed}_${pid}.sh
@@ -137,14 +141,15 @@ farmer_sow() {
 		sleep 10;
 	done
 	echo -e "\nInfo: No active threads"
-	echo -e "\nPrinting out execution summary. Please wait"
+	echo -e "\nPrinting execution summary. Please wait"
 	sleep 3
 	echo -e "\nSUMMARY:"
 	echo -e "------------------------------------------------"
+	TOTAL=`cat $canal_dir/${seed}_${pid}.sh | grep "farm:::success" | wc -l`
 	for i in `find $canal_dir -type f | grep "${pid}.log"`
 	do
 		echo -e " Seed log: `echo $i | rev | cut -d"/" -f1 | rev`"
-		TOTAL=`cat $canal_dir/${seed}_${pid}.sh | grep "farm:::success" | wc -l`
+		#TOTAL=`cat $canal_dir/${seed}_${pid}.sh | grep "farm:::success" | wc -l`
 		SUCCESS=`cat $i | grep "farm:::success" | grep -v "+" | wc -l`
 		FAILED=`cat $i | grep "farm:::failed" | grep -v "+" | wc -l`
 		echo -e " (${SUCCESS}) succeeded"
@@ -162,6 +167,8 @@ farmer_sow() {
 }
 
 farmer_harvest() {
+	echo ""
+        echo "// ** Invoking farmer 'harvest' sub-operation ** //"
         echo ""
 	echo "Harvesting crop and saving fruit"
 	echo "Info: Creating a snapshot of successful deployment"
@@ -195,8 +202,98 @@ farmer_harvest() {
 
 farmer_feed() {
 	echo ""
-	echo "We are still working on this feature. Stay tuned"
+        echo "// ** Invoking farmer 'feed' operation ** //"
 	echo ""
+	echo "Extracting seeds from fruit"
+	rm -rf ${canal_dir}/fruit-extract-${pid} &>/dev/null
+	mkdir -p ${canal_dir}/fruit-extract-${pid}
+	cp -r ${fruits_dir}/${fruit} ${canal_dir}/fruit-extract-${pid}
+	cd ${canal_dir}/fruit-extract-${pid}; tar -xf ${canal_dir}/fruit-extract-${pid}/${fruit}
+	if [ `find ${canal_dir}/fruit-extract-${pid} -name "hosts" -type f &>/dev/null; echo $?` -ne 0 ]; then
+		echo "Error: hosts file not found, fruit image may be corrupted"
+		exit 1
+	fi
+	if [ `find ${canal_dir}/fruit-extract-${pid} -name "remote_user" -type f &>/dev/null; echo $?` -ne 0 ]; then
+                echo "Error: user file not found, fruit image may be corrupted"
+                exit 1
+        fi
+	if [ `find ${canal_dir}/fruit-extract-${pid} -name "*.sh" -type f &>/dev/null; echo $?` -ne 0 ]; then
+                echo "Error: compiled script not found, fruit image may be corrupted"
+                exit 1
+        fi
+	hosts_file=`cd ${canal_dir}/fruit-extract-${pid}; find ${canal_dir}/fruit-extract-${pid} -name "hosts" -type f`
+	remote_user_file=`cd ${canal_dir}/fruit-extract-${pid}; find ${canal_dir}/fruit-extract-${pid} -name "remote_user" -type f`
+	run_script=`cd ${canal_dir}/fruit-extract-${pid}; find ${canal_dir}/fruit-extract-${pid} -name "*.sh" -type f`
+	short_fruit=`echo "$fruit" | rev | cut -d"-" -f5- | rev`
+	remote_user=`cat $remote_user_file`
+	echo "Seeds extracted successully from fruit"
+	echo -e "\nInfo: Checking seeds integrity"
+	while read hn;
+        do
+                status=$(ssh -n -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=5 $hn echo ok 2>/dev/null)
+                if [[ $status == ok ]] ; then
+                        echo "[$hn] SSH setup verified"
+                        ssh -n -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=5 $hn "id -u $remote_user" &>/dev/null
+                        if [ $? -ne 0 ]; then
+                                echo "[$hn] Remote user[$remote_user] do not exist"
+                                rc=1
+                        else
+                                echo "[$hn] Remote user[$remote_user] verified"
+                        fi
+
+                elif [[ $status == "Permission denied"* ]]; then
+                        echo "[$hn] SSH setup failed. Make sure passwordless ssh is established between current and remote hosts"
+                        rc=1
+                else
+                        echo "[$hn] SSH - Unable to connect"
+                        rc=1
+                fi
+        done < $hosts_file
+	if [[ $rc -eq 1 ]]; then
+		echo -e "\nError: Integrity check failed"
+		echo "Feed operation from fuit failed"
+		exit 1
+	else
+		echo -e "\nInfo: Integrity check success"
+	fi
+	echo -e "\nInfo: Farmer is deploying seeds in soils"
+	while read hn;
+        do
+                echo -e "\n Sowing seeds on host[$hn]"
+                ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=5 $hn 'bash -s -x' < $run_script &>${canal_dir}/${short_fruit}_${hn}_${pid}.log &
+                pstree -pan ${pid} | grep "${hn}" &>/dev/null
+                if [ $? -ne 0 ]; then
+                        echo "SSH remote connect failed on host[$hn]. Please retry again."
+                        continue
+                fi
+        done < $hosts_file
+	echo ""
+	sleep 5;
+        while [[ `pstree -pan ${pid} 2>/dev/null | grep "BatchMode=yes" | wc -l` -ne 1 ]];
+        do
+                BACKGP=`pstree -pan ${pid} 2>/dev/null | grep "BatchMode=yes" | wc -l`
+                echo "Info: Waitig on (${BACKGP}) active thread(s)"
+                sleep 10;
+        done
+        echo -e "\nInfo: No active threads"
+        echo -e "\nPrinting execution summary. Please wait"
+        sleep 3
+        echo -e "\nSUMMARY:"
+        echo -e "------------------------------------------------"
+	TOTAL=`cat $run_script | grep "farm:::success" | wc -l`
+        for i in `find $canal_dir -type f | grep "${pid}.log"`
+        do
+                echo -e " Fruit log: `echo $i | rev | cut -d"/" -f1 | rev`"
+                #TOTAL=`cat $run_script | grep "farm:::success" | wc -l`
+                SUCCESS=`cat $i | grep "farm:::success" | grep -v "+" | wc -l`
+                FAILED=`cat $i | grep "farm:::failed" | grep -v "+" | wc -l`
+                echo -e " (${SUCCESS}) succeeded"
+                echo -e " (${FAILED}) failed"
+                echo -e "\n Commands: Total (${TOTAL}) Succeeded (${SUCCESS}) Failed (${FAILED})"
+                echo -e "------------------------------------------------"
+        done
+	rm -rf ${canal_dir}/fruit-extract-${pid}
+        echo -e "\nCheck logs[${canal_dir}/${short_fruit}_*] for entire logs"
 }
 
 farmer_cleanup() {
@@ -205,8 +302,11 @@ farmer_cleanup() {
 	while [[ `pstree -pan ${pid} 2>/dev/null | wc -l` -ne 4 ]];
 	do
 		kill -9 `pstree -pan ${pid} 2>/dev/null | cut -d"," -f2 | cut -d" " -f1 | grep -v ${pid} | tr '\n' ' '` 2>/dev/null 1>/dev/null
-		rm $canal_dir/${seed}_${pid}.sh &>/dev/null
+		#rm $canal_dir/${seed}_${pid}.sh &>/dev/null
+		#rm -rf ${canal_dir}/fruit-extract-${pid}
 	done
+	rm $canal_dir/${seed}_${pid}.sh &>/dev/null
+	rm -rf ${canal_dir}/fruit-extract-${pid} &>/dev/null
 	echo "Process cleanup completed"
 	exit 1
 }
@@ -222,9 +322,10 @@ echo -e '
 | | | | (_) | (_| |  __/ | || (_| | |  | | | | | |  __/ |
 |_| |_|\___/ \__,_|\___| |_| \__,_|_|  |_| |_| |_|\___|_|
 
+	  Copyright (c) 2017 MANIKUMAR JUTTUKONDA
 
 Visit <https://disizjay.github.io/node-farmer/> for more details
-		// Current Build: v1.3.0 //
+		// Stable release: v2.0.0 //
 '
 
 if [ -n $BASH ]; then
@@ -303,22 +404,15 @@ case $1 in
 					exit 1;
 					;;
 			esac
-			#farmer_info
-			#if [[ $rc -eq 1 ]]; then
-                        #        echo "Error: Integrity check failed"
-                        #        echo "Good bye!"
-                        #        exit 1
-			#else
-			#	echo "Info: Integrity check success"
+			farmer_info
+			if [[ $rc -eq 1 ]]; then
+                                echo "Error: Integrity check failed"
+                                exit 1
+			else
+				echo "Info: Integrity check success"
 				farmer_sow
 				farmer_harvest
-				#if [ $? -eq 0 ]; then
-				#	farmer_harvest
-				#else
-				#	echo "Errors occured while sowing soil, deploying seed"
-				#	exit 1
-				#fi
-                        #fi
+                        fi
 		fi
 		;;
 	
