updated v1.1

diff --git a/farmer b/farmer
--- a/farmer
+++ b/farmer
@@ -30,7 +30,7 @@
 pid=$$
 whereami=`pwd`
 home=${whereami}
-cd ${home}; stat canal fruits soils seeds &>/dev/null; if [ $? -ne 0 ]; then echo -e "Error: Required directories(canal, fruits, soils, seeds) are missing. Please make sure to create required  directories in your current directory"; exit 1; fi
+#cd ${home}; stat canal fruits soils seeds &>/dev/null; if [ $? -ne 0 ]; then echo -e "Error: Required directories(canal, fruits, soils, seeds) are missing. Please make sure to create required  directories in your current directory"; exit 1; fi
 umask 0027
 seconds=0
 canal_dir="${home}/canal";
@@ -57,10 +57,8 @@ help() {
 	echo -e "\n// Examples //"
 	echo -e "   To dislay information about existing configuration"
 	echo -e "\t farmer info --user root --seed example-user-make --soil example-development"
-	echo ""
 	echo -e "   To run deployment"
         echo -e "\t farmer sow --user root --seed example-user-make --soil example-development"
-	echo ""
 	echo -e "   For help"
 	echo -e "\t farmer help"
 	echo ""
@@ -175,12 +173,25 @@ farmer_harvest() {
 #start
 trap farmer_cleanup SIGHUP SIGINT SIGTERM
 
+echo -e '
+                 _         __
+                | |       / _|
+ _ __   ___   __| | ___  | |_ __ _ _ __ _ __ ___   ___ _ __
+| '\''_ \ / _ \ / _` |/ _ \ |  _/ _` | '\''__| '\''_ ` _ \ / _ \ '\''__|
+| | | | (_) | (_| |  __/ | || (_| | |  | | | | | |  __/ |
+|_| |_|\___/ \__,_|\___| |_| \__,_|_|  |_| |_| |_|\___|_|
+
+
+Visit <https://disizjay.github.io/node-farmer/> for more details
+		// Current Build: v1.1 //
+'
+
 if [ -n $BASH ]; then
 	echo ""
-	echo "Check BASH: [SUCCESS]"
+	echo "Info: Check BASH: [SUCCESS]"
 else
 	echo ""
-	echo "Check BASH: [FAILED]"
+	echo "Info: Check BASH: [FAILED]"
 	echo "Error #99: BASH required to run farmer"
 	exit 1
 fi
@@ -196,18 +207,6 @@ elif [ $# -gt 7 ]; then
 	help
 	exit 1;
 fi
-
-echo -e '
-              __                                      __   ___
-             / _|                                    /_ | / _ \
-            | |_ __ _ _ __ _ __ ___   ___ _ __  __   _| || | | |
-            |  _/ _` | '\''__| '\''_ ` _ \ / _ \ '\''__| \ \ / / || | | |
-            | || (_| | |  | | | | | |  __/ |     \ V /| || |_| |
-            |_| \__,_|_|  |_| |_| |_|\___|_|      \_/ |_(_)___/
-
-         Visit <https://disizjay.github.io/farmer/> for more details
-			    Current Build: v1.0.4	
-'
 
 #kickstart
 case $1 in
