updated v2.0.1

diff --git a/farmer b/farmer
--- a/farmer
+++ b/farmer
@@ -119,8 +119,8 @@ farmer_sow() {
 	do
 	echo "" >> $canal_dir/${seed}_${pid}.sh
 	echo "#${i}" >> $canal_dir/${seed}_${pid}.sh
-	cat $i | grep "arg" | awk -F":::" '{print $2}' >> $canal_dir/${seed}_${pid}.sh
-	cat $i | grep "command" | awk -F":::" '{print $2}' | awk '{print $0, "; if [ $? -ne 0 ]; then echo 'farm:::failed'; exit 1; else echo 'farm:::success'; fi"}' >> $canal_dir/${seed}_${pid}.sh
+	cat $i | grep "arg:::" | awk -F":::" '{print $2}' >> $canal_dir/${seed}_${pid}.sh
+	cat $i | grep "command:::" | awk -F":::" '{print $2}' | awk '{print $0, "\nif [ $? -ne 0 ]; then echo 'farm:::failed'; exit 1; else echo 'farm:::success'; fi"}' >> $canal_dir/${seed}_${pid}.sh
 	done
 	while read hn;
 	do
@@ -226,7 +226,7 @@ farmer_feed() {
 	run_script=`cd ${canal_dir}/fruit-extract-${pid}; find ${canal_dir}/fruit-extract-${pid} -name "*.sh" -type f`
 	short_fruit=`echo "$fruit" | rev | cut -d"-" -f5- | rev`
 	remote_user=`cat $remote_user_file`
-	echo "Seeds extracted successully from fruit"
+	echo "Seeds extracted successully"
 	echo -e "\nInfo: Checking seeds integrity"
 	while read hn;
         do
@@ -325,19 +325,10 @@ echo -e '
 	  Copyright (c) 2017 MANIKUMAR JUTTUKONDA
 
 Visit <https://disizjay.github.io/node-farmer/> for more details
-		// Stable release: v2.0.0 //
+		// Stable release: v2.0.1 //
 '
 
-if [ -n $BASH ]; then
-	echo ""
-	echo "Info: BASH check [OK]"
-else
-	echo ""
-	echo "Info: BASH check [FAILED]"
-	echo "Error #99: BASH required to run farmer"
-	exit 1
-fi
-
+# argument check
 if [ $# -lt 1 ]; then
 	echo ""
 	echo "Error #101: Not enough arguments"
@@ -348,6 +339,63 @@ elif [ $# -gt 7 ]; then
 	echo "Error #102: Too many aruments"
 	help
 	exit 1;
+fi
+
+# dependency check
+if ! $(which bash &>/dev/null); then
+        echo ""
+        echo "Error: 'bash' command not found"
+        echo "Error: 'bash' dependency must be resolved inorder to continue"
+        exit 1
+fi
+
+if ! $(which pstree &>/dev/null); then
+	echo ""
+	echo "Error: 'pstree' command not found"
+	echo "Error: 'pstree' dependency must be resolved inorder to continue"
+	exit 1
+fi
+
+if ! $(which ssh &>/dev/null); then
+        echo ""
+        echo "Error: 'ssh' command not found"
+        echo "Error: 'ssh' dependency must be resolved inorder to continue"
+        exit 1
+fi
+
+if ! $(which grep &>/dev/null); then
+        echo ""
+        echo "Error: 'grep' command not found"
+        echo "Error: 'grep' dependency must be resolved inorder to continue"
+        exit 1
+fi
+
+if ! $(which awk &>/dev/null); then
+        echo ""
+        echo "Error: 'awk' command not found"
+        echo "Error: 'awk' dependency must be resolved inorder to continue"
+        exit 1
+fi
+
+if ! $(which sed &>/dev/null); then
+        echo ""
+        echo "Error: 'sed' command not found"
+        echo "Error: 'sed' dependency must be resolved inorder to continue"
+        exit 1
+fi
+
+if ! $(which find &>/dev/null); then
+        echo ""
+        echo "Error: 'find' command not found"
+        echo "Error: 'find' dependency must be resolved inorder to continue"
+        exit 1
+fi
+
+if ! $(which kill &>/dev/null); then
+        echo ""
+        echo "Error: 'kill' command not found"
+        echo "Error: 'kill' dependency must be resolved inorder to continue"
+        exit 1
 fi
 
 # kickstart
